project_id = "wjaeqrhhqzosuxfackpg"

[functions.wms-proxy]
verify_jwt = false

[functions.geo-chat]
verify_jwt = false

[functions.sync-wells]
verify_jwt = false

[functions.wells-query]
verify_jwt = false
